Pids for login
smartfrog-oss/frogkit pull request #25
Opened 2019-01-18 15:03 UTC by Tehreemnaz1

2019-01-18 15:04 UTC, pierpaoloferraro submitted a review, later dismissed

2019-01-18 15:12 UTC, pierpaoloferraro submitted a review, later dismissed

2019-01-21 14:23 UTC, mouafa requested changes
please use the component name, `header` in this case as a prefix for the pid.
example `emailaddress` will be `header.email`

2019-01-22 10:29 UTC, mouafa approved these changes

2019-01-22 13:39 UTC, merged